### ISSUE TITLE
编译缺少包 restweb

### ISSUE THREAD

**Issue by riba2534** [ZJGSU-Open-Source/GoOnlineJudge#63]
请问 restweb 是某一个框架，还是哪个包?

**Comment by clarkzjw** [comment]
restweb的repo在https://github.com/sakeven/restweb 

您可以按照README中的[步骤](https://github.com/ZJGSU-Open-Source/GoOnlineJudge/blob/master/README.md#install)依次进行编译和安装。

**Comment by riba2534** [comment]
感谢回答，repo的地址确实在install.sh里面有，没注意看。此项目是否会继续维护下去呢，比如升级为 go mod 管理

**Comment by clarkzjw** [comment]
这个项目建立的最早的初衷是还在校期间为学校的OJ系统进行重构。后续如果要继续维护的话可能会transfer/fork到别的组织或者帐号下，但是短期内不会有这个打算。
